import type {Metadata} from 'next';
import './globals.css';
import {GTProvider} from 'gt-next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GTProvider>{children}</GTProvider>
      </body>
    </html>
  );
}
